package vars

import "fmt"

// OperatorInfo 运营商详细信息结构体
type OperatorInfo struct {
	MCC         string   // Mobile Country Code 移动国家代码
	MNC         string   // Mobile Network Code 移动网络代码
	CountryCode string   // 国际电话区号
	CountryEN   string   // 国家英文名称
	CountryCN   string   // 国家中文名称
	BrandEN     string   // 运营商英文品牌
	BrandCN     string   // 运营商中文品牌
	CompanyEN   string   // 公司英文全称
	CompanyCN   string   // 公司中文全称
	Status      string   // 状态: Operational(运营中), Planned(计划中), Inactive(不活跃)
	Technology  []string // 网络技术: GSM, UMTS, LTE, NR, CDMA, etc.
	Bands       []string // 频段信息
	Area        string   // 覆盖区域
	LaunchYear  int      // 推出年份
	Website     string   // 官方网站
	Notes       string   // 备注
}

// 全球主要运营商信息数据库
var GlobalOperators = map[string]OperatorInfo{
	// 中国运营商
	"46000": {
		MCC:         "460",
		MNC:         "00",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Mobile",
		BrandCN:     "中国移动",
		CompanyEN:   "China Mobile Communications Corporation",
		CompanyCN:   "中国移动通信集团公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "TD-SCDMA", "TD-LTE", "NR"},
		Bands:       []string{"GSM 900/1800", "B34", "B39", "B41", "n41", "n79"},
		Area:        "全国",
		LaunchYear:  2000,
		Website:     "https://www.10086.cn",
		Notes:       "全球用户数最多的移动运营商",
	},
	"46001": {
		MCC:         "460",
		MNC:         "01",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Mobile",
		BrandCN:     "中国移动",
		CompanyEN:   "China Mobile Communications Corporation",
		CompanyCN:   "中国移动通信集团公司",
		Status:      "Operational",
		Technology:  []string{"TD-SCDMA", "TD-LTE", "NR"},
		Bands:       []string{"B34", "B39", "B41", "n41"},
		Area:        "全国",
		LaunchYear:  2000,
		Website:     "https://www.10086.cn",
		Notes:       "中国移动4G/5G专用代码",
	},
	"46003": {
		MCC:         "460",
		MNC:         "03",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Telecom",
		BrandCN:     "中国电信",
		CompanyEN:   "China Telecommunications Corporation",
		CompanyCN:   "中国电信集团公司",
		Status:      "Operational",
		Technology:  []string{"CDMA2000", "LTE", "NR"},
		Bands:       []string{"CDMA 800", "B1", "B3", "B5", "n78"},
		Area:        "全国",
		LaunchYear:  2008,
		Website:     "https://www.189.cn",
		Notes:       "最早使用CDMA技术的中国运营商",
	},
	"46006": {
		MCC:         "460",
		MNC:         "06",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Unicom",
		BrandCN:     "中国联通",
		CompanyEN:   "China United Network Communications Group Co., Ltd.",
		CompanyCN:   "中国联合网络通信集团有限公司",
		Status:      "Operational",
		Technology:  []string{"WCDMA", "LTE", "NR"},
		Bands:       []string{"WCDMA 2100", "B1", "B3", "B8", "n78"},
		Area:        "全国",
		LaunchYear:  2009,
		Website:     "https://www.10010.com",
		Notes:       "中国主要的WCDMA运营商",
	},
	"46011": {
		MCC:         "460",
		MNC:         "11",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Telecom",
		BrandCN:     "中国电信",
		CompanyEN:   "China Telecommunications Corporation",
		CompanyCN:   "中国电信集团公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B1", "B3", "B5", "B8", "n78", "n1"},
		Area:        "全国",
		LaunchYear:  2019,
		Website:     "https://www.189.cn",
		Notes:       "中国电信5G网络专用代码",
	},
	"46015": {
		MCC:         "460",
		MNC:         "15",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Broadnet",
		BrandCN:     "中国广电",
		CompanyEN:   "China Broadcasting Network Corporation",
		CompanyCN:   "中国广播电视网络有限公司",
		Status:      "Operational",
		Technology:  []string{"NR"},
		Bands:       []string{"n28", "n79", "n41"},
		Area:        "全国",
		LaunchYear:  2020,
		Website:     "https://www.10099.com",
		Notes:       "中国第四大5G运营商，拥有700MHz频段",
	},
	"46002": {
		MCC:         "460",
		MNC:         "02",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Unicom",
		BrandCN:     "中国联通",
		CompanyEN:   "China United Network Communications Group Co., Ltd.",
		CompanyCN:   "中国联合网络通信集团有限公司",
		Status:      "Operational",
		Technology:  []string{"WCDMA", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B8", "n78"},
		Area:        "全国",
		LaunchYear:  2010,
		Website:     "https://www.10010.com",
		Notes:       "中国联通4G/5G专用代码",
	},
	"46004": {
		MCC:         "460",
		MNC:         "04",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Mobile Satellite",
		BrandCN:     "中国移动卫星",
		CompanyEN:   "China Mobile Communications Corporation",
		CompanyCN:   "中国移动通信集团公司",
		Status:      "Operational",
		Technology:  []string{"Satellite"},
		Bands:       []string{"L/S-Band"},
		Area:        "全国",
		LaunchYear:  2000,
		Website:     "https://www.10086.cn",
		Notes:       "中国移动卫星通信服务",
	},
	"46007": {
		MCC:         "460",
		MNC:         "07",
		CountryCode: "+86",
		CountryEN:   "China",
		CountryCN:   "中国",
		BrandEN:     "China Mobile",
		BrandCN:     "中国移动",
		CompanyEN:   "China Mobile Communications Corporation",
		CompanyCN:   "中国移动通信集团公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B38", "B39", "B40", "B41", "n78", "n79"},
		Area:        "全国",
		LaunchYear:  2014,
		Website:     "https://www.10086.cn",
		Notes:       "中国移动4G/5G网络专用代码",
	},

	// 美国主要运营商
	"310260": {
		MCC:         "310",
		MNC:         "260",
		CountryCode: "+1",
		CountryEN:   "United States",
		CountryCN:   "美国",
		BrandEN:     "T-Mobile US",
		BrandCN:     "T-Mobile美国",
		CompanyEN:   "T-Mobile US, Inc.",
		CompanyCN:   "T-Mobile美国公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B2", "B4", "B12", "B66", "B71", "n41", "n71"},
		Area:        "全美",
		LaunchYear:  2001,
		Website:     "https://www.t-mobile.com",
		Notes:       "美国第三大移动运营商，2020年与Sprint合并",
	},
	"310120": {
		MCC:         "310",
		MNC:         "120",
		CountryCode: "+1",
		CountryEN:   "United States",
		CountryCN:   "美国",
		BrandEN:     "Sprint (now T-Mobile)",
		BrandCN:     "Sprint(现T-Mobile)",
		CompanyEN:   "Sprint Corporation (acquired by T-Mobile US)",
		CompanyCN:   "Sprint公司(被T-Mobile美国收购)",
		Status:      "Merged",
		Technology:  []string{"CDMA2000", "LTE", "NR"},
		Bands:       []string{"B25", "B26", "B41", "n41"},
		Area:        "全美",
		LaunchYear:  1996,
		Website:     "https://www.t-mobile.com",
		Notes:       "2020年被T-Mobile收购，网络正在整合中",
	},
	"310410": {
		MCC:         "310",
		MNC:         "410",
		CountryCode: "+1",
		CountryEN:   "United States",
		CountryCN:   "美国",
		BrandEN:     "AT&T",
		BrandCN:     "AT&T",
		CompanyEN:   "AT&T Mobility",
		CompanyCN:   "AT&T移动",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B2", "B4", "B5", "B12", "B14", "B30", "n5", "n260"},
		Area:        "全美",
		LaunchYear:  2000,
		Website:     "https://www.att.com",
		Notes:       "美国第二大移动运营商，前身为Cingular Wireless",
	},
	"311480": {
		MCC:         "311",
		MNC:         "480",
		CountryCode: "+1",
		CountryEN:   "United States",
		CountryCN:   "美国",
		BrandEN:     "Verizon Wireless",
		BrandCN:     "Verizon无线",
		CompanyEN:   "Verizon Communications",
		CompanyCN:   "Verizon通信公司",
		Status:      "Operational",
		Technology:  []string{"CDMA2000", "LTE", "NR"},
		Bands:       []string{"B2", "B4", "B5", "B13", "B66", "n2", "n5", "n66", "n261"},
		Area:        "全美",
		LaunchYear:  2000,
		Website:     "https://www.verizon.com",
		Notes:       "美国第一大移动运营商，CDMA网络已关闭",
	},

	// 欧盟主要运营商
	"26201": {
		MCC:         "262",
		MNC:         "01",
		CountryCode: "+49",
		CountryEN:   "Germany",
		CountryCN:   "德国",
		BrandEN:     "Telekom Deutschland",
		BrandCN:     "德国电信",
		CompanyEN:   "Deutsche Telekom AG",
		CompanyCN:   "德国电信股份公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B3", "B7", "B20", "B28", "n1", "n78"},
		Area:        "德国",
		LaunchYear:  1992,
		Website:     "https://www.telekom.de",
		Notes:       "欧洲最大电信公司之一，品牌为T-Mobile",
	},
	"20801": {
		MCC:         "208",
		MNC:         "01",
		CountryCode: "+33",
		CountryEN:   "France",
		CountryCN:   "法国",
		BrandEN:     "Orange France",
		BrandCN:     "Orange法国",
		CompanyEN:   "Orange S.A.",
		CompanyCN:   "Orange公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B3", "B7", "B20", "B28", "n78"},
		Area:        "法国",
		LaunchYear:  1994,
		Website:     "https://www.orange.fr",
		Notes:       "法国第一大移动运营商，全球Orange品牌的一部分",
	},
	"23415": {
		MCC:         "234",
		MNC:         "15",
		CountryCode: "+44",
		CountryEN:   "United Kingdom",
		CountryCN:   "英国",
		BrandEN:     "Vodafone UK",
		BrandCN:     "Vodafone英国",
		CompanyEN:   "Vodafone Group Plc",
		CompanyCN:   "沃达丰集团",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B7", "B20", "B32", "n78"},
		Area:        "英国",
		LaunchYear:  1991,
		Website:     "https://www.vodafone.co.uk",
		Notes:       "英国三大移动运营商之一，全球Vodafone网络的一部分",
	},
	"22201": {
		MCC:         "222",
		MNC:         "01",
		CountryCode: "+39",
		CountryEN:   "Italy",
		CountryCN:   "意大利",
		BrandEN:     "TIM (Telecom Italia Mobile)",
		BrandCN:     "意大利电信移动",
		CompanyEN:   "Telecom Italia S.p.A.",
		CompanyCN:   "意大利电信公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B3", "B7", "B20", "B28", "n78"},
		Area:        "意大利",
		LaunchYear:  1995,
		Website:     "https://www.tim.it",
		Notes:       "意大利第一大移动运营商",
	},
	"26202": {
		MCC:         "262",
		MNC:         "02",
		CountryCode: "+49",
		CountryEN:   "Germany",
		CountryCN:   "德国",
		BrandEN:     "Vodafone Germany",
		BrandCN:     "Vodafone德国",
		CompanyEN:   "Vodafone Germany GmbH",
		CompanyCN:   "Vodafone德国公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B7", "B20", "B28", "n78"},
		Area:        "德国",
		LaunchYear:  1992,
		Website:     "https://www.vodafone.de",
		Notes:       "德国第二大移动运营商",
	},
	"23430": {
		MCC:         "234",
		MNC:         "30",
		CountryCode: "+44",
		CountryEN:   "United Kingdom",
		CountryCN:   "英国",
		BrandEN:     "EE",
		BrandCN:     "EE",
		CompanyEN:   "EE Limited",
		CompanyCN:   "EE公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B7", "B20", "B28", "n78"},
		Area:        "英国",
		LaunchYear:  2010,
		Website:     "https://www.ee.co.uk",
		Notes:       "英国最大移动运营商，BT集团旗下",
	},
	"23420": {
		MCC:         "234",
		MNC:         "20",
		CountryCode: "+44",
		CountryEN:   "United Kingdom",
		CountryCN:   "英国",
		BrandEN:     "Three UK",
		BrandCN:     "Three英国",
		CompanyEN:   "Three UK Limited",
		CompanyCN:   "Three英国公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B7", "B20", "B28", "n78"},
		Area:        "英国",
		LaunchYear:  2003,
		Website:     "https://www.three.co.uk",
		Notes:       "英国三大移动运营商之一，主打无限数据套餐",
	},

	// 亚洲其他国家运营商
	"44000": {
		MCC:         "440",
		MNC:         "00",
		CountryCode: "+81",
		CountryEN:   "Japan",
		CountryCN:   "日本",
		BrandEN:     "NTT Docomo",
		BrandCN:     "NTT Docomo",
		CompanyEN:   "Nippon Telegraph and Telephone Corporation",
		CompanyCN:   "日本电报电话公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B1", "B3", "B19", "B21", "B28", "n77", "n78", "n79"},
		Area:        "日本",
		LaunchYear:  1992,
		Website:     "https://www.nttdocomo.co.jp",
		Notes:       "日本第一大移动运营商，曾发明i-mode服务",
	},
	"44001": {
		MCC:         "440",
		MNC:         "01",
		CountryCode: "+81",
		CountryEN:   "Japan",
		CountryCN:   "日本",
		BrandEN:     "NTT Docomo",
		BrandCN:     "NTT Docomo",
		CompanyEN:   "Nippon Telegraph and Telephone Corporation",
		CompanyCN:   "日本电报电话公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B1", "B3", "B19", "B21", "B28", "n77", "n78", "n79"},
		Area:        "日本",
		LaunchYear:  1992,
		Website:     "https://www.nttdocomo.co.jp",
		Notes:       "NTT Docomo主要MNC代码",
	},
	"44010": {
		MCC:         "440",
		MNC:         "10",
		CountryCode: "+81",
		CountryEN:   "Japan",
		CountryCN:   "日本",
		BrandEN:     "SoftBank",
		BrandCN:     "软银",
		CompanyEN:   "SoftBank Corp.",
		CompanyCN:   "软银公司",
		Status:      "Operational",
		Technology:  []string{"WCDMA", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B8", "B41", "n77", "n78"},
		Area:        "日本",
		LaunchYear:  2006,
		Website:     "https://www.softbank.jp",
		Notes:       "日本第三大移动运营商",
	},
	"44020": {
		MCC:         "440",
		MNC:         "20",
		CountryCode: "+81",
		CountryEN:   "Japan",
		CountryCN:   "日本",
		BrandEN:     "SoftBank",
		BrandCN:     "软银",
		CompanyEN:   "SoftBank Corp.",
		CompanyCN:   "软银公司",
		Status:      "Operational",
		Technology:  []string{"WCDMA", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B8", "B41", "n77", "n78"},
		Area:        "日本",
		LaunchYear:  2006,
		Website:     "https://www.softbank.jp",
		Notes:       "SoftBank主要MNC代码",
	},
	"44050": {
		MCC:         "440",
		MNC:         "50",
		CountryCode: "+81",
		CountryEN:   "Japan",
		CountryCN:   "日本",
		BrandEN:     "KDDI (au)",
		BrandCN:     "KDDI(au)",
		CompanyEN:   "KDDI Corporation",
		CompanyCN:   "KDDI公司",
		Status:      "Operational",
		Technology:  []string{"CDMA2000", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B11", "B18", "B26", "B28", "n77", "n78"},
		Area:        "日本",
		LaunchYear:  1988,
		Website:     "https://www.au.com",
		Notes:       "日本第二大移动运营商，品牌为au",
	},
	"45005": {
		MCC:         "450",
		MNC:         "05",
		CountryCode: "+82",
		CountryEN:   "South Korea",
		CountryCN:   "韩国",
		BrandEN:     "SK Telecom",
		BrandCN:     "SK电讯",
		CompanyEN:   "SK Telecom Co., Ltd.",
		CompanyCN:   "SK电讯公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B1", "B3", "B5", "B7", "B8", "n1", "n78"},
		Area:        "韩国",
		LaunchYear:  1984,
		Website:     "https://www.sktelecom.com",
		Notes:       "韩国第一大移动运营商，5G部署领先",
	},
	"45006": {
		MCC:         "450",
		MNC:         "06",
		CountryCode: "+82",
		CountryEN:   "South Korea",
		CountryCN:   "韩国",
		BrandEN:     "KT (Korea Telecom)",
		BrandCN:     "KT",
		CompanyEN:   "KT Corporation",
		CompanyCN:   "KT公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B1", "B3", "B5", "B7", "B8", "n1", "n78"},
		Area:        "韩国",
		LaunchYear:  1996,
		Website:     "https://www.kt.com",
		Notes:       "韩国第二大移动运营商",
	},
	"45008": {
		MCC:         "450",
		MNC:         "08",
		CountryCode: "+82",
		CountryEN:   "South Korea",
		CountryCN:   "韩国",
		BrandEN:     "LG U+",
		BrandCN:     "LG U+",
		CompanyEN:   "LG Uplus Corporation",
		CompanyCN:   "LG U+公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B1", "B3", "B5", "B7", "B8", "n1", "n78"},
		Area:        "韩国",
		LaunchYear:  1996,
		Website:     "https://www.uplus.co.kr",
		Notes:       "韩国第三大移动运营商，5G发展迅速",
	},
	"52501": {
		MCC:         "525",
		MNC:         "01",
		CountryCode: "+65",
		CountryEN:   "Singapore",
		CountryCN:   "新加坡",
		BrandEN:     "Singtel",
		BrandCN:     "新加坡电信",
		CompanyEN:   "Singapore Telecommunications Limited",
		CompanyCN:   "新加坡电信有限公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B3", "B7", "B8", "B28", "B40", "n1", "n78"},
		Area:        "新加坡",
		LaunchYear:  1992,
		Website:     "https://www.singtel.com",
		Notes:       "新加坡第一大电信运营商，在亚洲多国有投资",
	},
	"50219": {
		MCC:         "502",
		MNC:         "19",
		CountryCode: "+60",
		CountryEN:   "Malaysia",
		CountryCN:   "马来西亚",
		BrandEN:     "Celcom",
		BrandCN:     "天地通",
		CompanyEN:   "Celcom Axiata Berhad",
		CompanyCN:   "Celcom Axiata公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B3", "B5", "B7", "B8", "B28", "B40", "n78"},
		Area:        "马来西亚",
		LaunchYear:  1988,
		Website:     "https://www.celcom.com.my",
		Notes:       "马来西亚历史最悠久的移动运营商",
	},
	"405800": {
		MCC:         "405",
		MNC:         "800",
		CountryCode: "+91",
		CountryEN:   "India",
		CountryCN:   "印度",
		BrandEN:     "Reliance Jio",
		BrandCN:     "Reliance Jio",
		CompanyEN:   "Reliance Jio Infocomm Limited",
		CompanyCN:   "Reliance Jio信息通信公司",
		Status:      "Operational",
		Technology:  []string{"LTE", "NR"},
		Bands:       []string{"B3", "B5", "B40", "B41", "n78"},
		Area:        "印度",
		LaunchYear:  2016,
		Website:     "https://www.jio.com",
		Notes:       "印度最大的4G/5G运营商，免费4G服务颠覆市场",
	},

	// 其他地区运营商
	"50501": {
		MCC:         "505",
		MNC:         "01",
		CountryCode: "+61",
		CountryEN:   "Australia",
		CountryCN:   "澳大利亚",
		BrandEN:     "Telstra",
		BrandCN:     "澳洲电信",
		CompanyEN:   "Telstra Corporation Limited",
		CompanyCN:   "澳洲电信有限公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B3", "B5", "B7", "B8", "B28", "n78"},
		Area:        "澳大利亚",
		LaunchYear:  1993,
		Website:     "https://www.telstra.com.au",
		Notes:       "澳大利亚最大电信公司，网络覆盖最广",
	},
	"72405": {
		MCC:         "724",
		MNC:         "05",
		CountryCode: "+55",
		CountryEN:   "Brazil",
		CountryCN:   "巴西",
		BrandEN:     "Claro Brasil",
		BrandCN:     "Claro巴西",
		CompanyEN:   "América Móvil",
		CompanyCN:   "美洲移动公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE"},
		Bands:       []string{"B2", "B4", "B5", "B7", "B28"},
		Area:        "巴西",
		LaunchYear:  2003,
		Website:     "https://www.claro.com.br",
		Notes:       "巴西主要移动运营商之一，墨西哥美洲移动旗下",
	},
	"302720": {
		MCC:         "302",
		MNC:         "720",
		CountryCode: "+1",
		CountryEN:   "Canada",
		CountryCN:   "加拿大",
		BrandEN:     "Rogers Wireless",
		BrandCN:     "Rogers无线",
		CompanyEN:   "Rogers Communications",
		CompanyCN:   "Rogers通信公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B2", "B4", "B5", "B7", "B12", "B13", "B17", "n66", "n71"},
		Area:        "加拿大",
		LaunchYear:  1985,
		Website:     "https://www.rogers.com",
		Notes:       "加拿大最大移动运营商之一",
	},
	"45400": {
		MCC:         "454",
		MNC:         "00",
		CountryCode: "+852",
		CountryEN:   "Hong Kong",
		CountryCN:   "香港",
		BrandEN:     "CSL",
		BrandCN:     "CSL",
		CompanyEN:   "CSL Mobile Limited",
		CompanyCN:   "CSL移动有限公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B8", "B28", "n78"},
		Area:        "香港",
		LaunchYear:  1983,
		Website:     "https://www.csl.com.hk",
		Notes:       "香港主要移动运营商之一",
	},
	"45406": {
		MCC:         "454",
		MNC:         "06",
		CountryCode: "+852",
		CountryEN:   "Hong Kong",
		CountryCN:   "香港",
		BrandEN:     "SmarTone",
		BrandCN:     "数码通",
		CompanyEN:   "SmarTone Mobile Communications Limited",
		CompanyCN:   "数码通移动通信有限公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B8", "B28", "n78"},
		Area:        "香港",
		LaunchYear:  1992,
		Website:     "https://www.smar-tone.com",
		Notes:       "香港主要移动运营商之一",
	},
	"45412": {
		MCC:         "454",
		MNC:         "12",
		CountryCode: "+852",
		CountryEN:   "Hong Kong",
		CountryCN:   "香港",
		BrandEN:     "China Mobile Hong Kong",
		BrandCN:     "中国移动香港",
		CompanyEN:   "China Mobile Hong Kong Company Limited",
		CompanyCN:   "中国移动香港有限公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B8", "B28", "n78"},
		Area:        "香港",
		LaunchYear:  1997,
		Website:     "https://www.hk.chinamobile.com",
		Notes:       "中国移动在香港的业务",
	},
	"65501": {
		MCC:         "655",
		MNC:         "01",
		CountryCode: "+27",
		CountryEN:   "South Africa",
		CountryCN:   "南非",
		BrandEN:     "Vodacom",
		BrandCN:     "Vodacom南非",
		CompanyEN:   "Vodacom Group Limited",
		CompanyCN:   "Vodacom集团公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE"},
		Bands:       []string{"B1", "B3", "B8", "B20", "B28"},
		Area:        "南非",
		LaunchYear:  1994,
		Website:     "https://www.vodacom.co.za",
		Notes:       "南非第一大移动运营商，Vodafone集团持股",
	},

	// 虚拟移动网络运营商 (MVNO)
	"MVNO-GOOGLE-FI": {
		MCC:         "310",
		MNC:         "260",
		CountryCode: "+1",
		CountryEN:   "United States",
		CountryCN:   "美国",
		BrandEN:     "Google Fi",
		BrandCN:     "Google Fi",
		CompanyEN:   "Google LLC",
		CompanyCN:   "谷歌公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B2", "B4", "B12", "B66", "B71", "n41", "n71"},
		Area:        "全美及国际漫游",
		LaunchYear:  2015,
		Website:     "https://fi.google.com",
		Notes:       "[MVNO] Google虚拟运营商，使用T-Mobile(310:260)、US Cellular(311:580)等网络",
	},
	"MVNO-GIFFGAFF": {
		MCC:         "234",
		MNC:         "02",
		CountryCode: "+44",
		CountryEN:   "United Kingdom",
		CountryCN:   "英国",
		BrandEN:     "Giffgaff",
		BrandCN:     "Giffgaff",
		CompanyEN:   "Giffgaff Limited",
		CompanyCN:     "Giffgaff有限公司",
		Status:      "Operational",
		Technology:  []string{"GSM", "UMTS", "LTE", "NR"},
		Bands:       []string{"B1", "B3", "B7", "B20", "B28", "n78"},
		Area:        "英国",
		LaunchYear:  2009,
		Website:     "https://www.giffgaff.com",
		Notes:       "[MVNO] 英国虚拟运营商，使用O2(234:02)网络，主打低价套餐",
	},
}

// 根据PLMN代码获取运营商信息
func GetOperatorInfo(plmn string) OperatorInfo {
	info, exists := GlobalOperators[plmn]
	if exists {
		return info
	}
	return OperatorInfo{}
}

// 根据MCC获取该国家所有运营商
func GetOperatorsByMCC(mcc string) []OperatorInfo {
	var operators []OperatorInfo
	for plmn, info := range GlobalOperators {
		// PLMN代码的前三位是MCC
		if len(plmn) >= 3 && plmn[0:3] == mcc {
			operators = append(operators, info)
		}
	}
	return operators
}

// 根据国家中文名称查找运营商
func GetOperatorsByCountryCN(countryCN string) []OperatorInfo {
	var operators []OperatorInfo
	for _, info := range GlobalOperators {
		if info.CountryCN == countryCN {
			operators = append(operators, info)
		}
	}
	return operators
}

// 根据品牌名称查找运营商
func GetOperatorsByBrand(brandCN string) []OperatorInfo {
	var operators []OperatorInfo
	for _, info := range GlobalOperators {
		if info.BrandCN == brandCN {
			operators = append(operators, info)
		}
	}
	return operators
}

// 运营商信息格式化输出
var operatorFormatter = `
运营商代码: %s-%s
国家: %s (%s) 电话区号: %s
运营商: %s (%s)
公司: %s (%s)
状态: %s
技术: %v
频段: %v
覆盖区域: %s
推出年份: %d
网站: %s
备注: %s
`

// 格式化输出运营商信息
func FormatOperatorInfo(info OperatorInfo) string {
	return fmt.Sprintf(operatorFormatter,
		info.MCC, info.MNC,
		info.CountryCN, info.CountryEN, info.CountryCode,
		info.BrandCN, info.BrandEN,
		info.CompanyCN, info.CompanyEN,
		info.Status,
		info.Technology,
		info.Bands,
		info.Area,
		info.LaunchYear,
		info.Website,
		info.Notes,
	)
}
